- reference/admin.yaml
- src/admin/paths/admin@projects@bulk.yaml
- src/components/schemas/project.yaml
Expose `category_ids` and `approver_emails` key in platform POST and bulk POST projects API.
Clickup link: https://app.clickup.com/t/85zrhfv01
> Release 2 & 3: Expose approver_emails and category_ids in projects post and bulk post request payload

- README.md
- reference/admin.yaml
- src/components/schemas/project.yaml
Add more info for restricted_spender_user_ids key in projects API.
Before:
After:
> Add more info for restricted_spender_user_ids key in projects API

- README.md
- reference/admin.yaml
- src/components/schemas/category.yaml
Description:
Add is_enabled key as optional + Add info that name and sub category cannot be same
Clickup: https://app.clickup.com/t/85zrnr59e
Old:
POST /admin/categories
POST /admin/categories/bulk
New:
POST /admin/categories
POST /admin/categories/bulk
> fix: Add is_enabled key as optional + Add info that name and sub category cannot be same

- reference/admin.yaml
- src/components/schemas/mileage_rate.yaml
ClickUp - https://app.clickup.com/t/85zrthjfm
- Currently the admin mileage rates POST API doc doesn't reflect the `required` fields needed in the payload.
- Added `required` in the fields that are mandatory for the API.
> fix: Updated admin mileage rate API doc to reflect required payload

- admin.yaml
- reference/admin.yaml
- src/components/schemas/employee.yaml
- src/components/schemas/fields.yaml
- src/components/schemas/invitation.yaml
- Added following new keys in `POST admin/employees/invite/bulk`
- locale
- mileage_settings
- delegatee_emails
- Removed redundant declarations of `locale` and `mileage_settings` keys
- `type: array` should have `maxItems` as key, not `maxLength`, fixed that
> feat: Add new keys in `POST admin/employees/invite/bulk`

- reference/admin.yaml
- reference/approver.yaml
- src/admin/paths/admin@categories.yaml
- src/approver/paths/approver@categories.yaml
- src/components/schemas/category.yaml
Added restricted_spender_user_ids field in GET and POST categories APIs of approver and admin persona
https://app.clickup.com/t/85ztr63mu
> feat: Added restricted_spender_user_ids field in GET and POST categories APIs of approver and admin persona

- admin.yaml
- reference/accountant.yaml
- reference/admin.yaml
- reference/approver.yaml
- reference/common.yaml
- reference/hod.yaml
- reference/hop.yaml
- reference/spender.yaml
- src/components/schemas/offset.yaml
PC: https://app.clickup.com/t/85zu0ajzd
The customer was confused about why we showed a value of `1000` when the maximum limit for GET APIs was `200`.
Clickup: https://app.clickup.com/t/85zu1qmvv
> feat: Update `offset` description to display correct limit value

- reference/admin.yaml
- src/admin/paths/admin@expenses.yaml
- src/components/schemas/expense.yaml
- added `404` response for cases when `id` doesn't exist 
- removed fields from `required` and added note accordingly for tests
> fix: minor doc changes for POST `/admin/expenses`

- docs/concepts/oauth2-application.md
Fixed the broken link.
Before:
After:
> fix: Fix the blog link to oauth2

- reference/admin.yaml
- src/components/schemas/expense.yaml
Updated the docs of admin/expenses to view `file_ids` in the body.
click URL: https://app.clickup.com/t/86cun8r7y
The below images contain changes which would be made
> adding file_ids in admin_expense_in for POST of admin/expenses

- reference/admin.yaml
- src/components/schemas/spend_overview.yaml
Clickup: https://app.clickup.com/t/86cvgejcx
> feat: Add `card_nickname` to spend overview by corporate card API

- reference/admin.yaml
- src/components/schemas/fields.yaml
- src/components/schemas/invitation.yaml
https://app.clickup.com/t/86cvyz0t6
> feat: Add `delegatees` key to invitations POST + deprecation warning for old key

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/components/schemas/expense_rules.yaml
- src/components/schemas/fields.yaml
> Added spec for dependent fields in expesnse rules

- reference/admin.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@corporate_card_transactions@reassign@bulk.yaml
- src/components/schemas/corporate_card_transaction.yaml
https://app.clickup.com/t/86cwk5guf
> feat: Docs for `POST admin/corporate_card_transactions/reassign/bulk`

- reference/admin.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@corporate_card_transactions.yaml
- src/admin/paths/admin@corporate_cards@delete.yaml
https://app.clickup.com/t/86cwmzrh9
> feat: Docs for `POST admin/corporate_cards/delete`

- reference/admin.yaml
- reference/approver.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@expenses@bulk.yaml
- src/approver/openapi.yaml
- src/approver/paths/approver@expenses@bulk.yaml
- src/components/schemas/expense.yaml
We are adding support for POST /<admin/approver>/expenses/bulk
###POST /approver/expenses/bulk
Request body:
Response body:
###POST /admin/expenses/bulk
Request body:
Response body:
https://app.clickup.com/1864988/v/l/1rx8w-41176
> feat: POST /<admin/approver>/expenses/bulk

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/components/schemas/expense.yaml
- src/components/schemas/fields.yaml
We have added support for 6 fields in the POST /<role>/expenses. 
Roles: 
- Admin
- Approver
- Spender
Fields added:
- code
- mileage_rate_id
- mileage_is_round_trip
- hote_is_breakfast_provided
- commute_details_id
- commute_details
We have also added support for file_ids in POST /approver/expenses.
Supporting screenshots:
1. POST /spender/expenses 
- Code 
- Location fix
- Additional fields
2. POST /admin/expenses
- Code 
- Location fix
- Additional fields
3. POST /admin/expenses
- Code 
- Location fix
- Additional fields and file IDs support
https://app.clickup.com/1864988/v/l/1rx8w-41176
> feat: Additional fields POST /<role>/expenses

- reference/approver.yaml
- src/approver/openapi.yaml
- src/approver/paths/approver@mileage_rates.yaml
https://app.clickup.com/t/86cwtw4ve
> feat: Added doc for `GET /approver/mileage_rates`

- .github/workflows/bundler.yml
removing Github access token used in github actions in platform-docs
https://app.clickup.com/t/86cwxbfue
> fix: remove Github access token used in github actions

- reference/admin.yaml
- src/components/schemas/statements.yaml
feat: adding card_mapping key in create_card_transactions API
https://app.clickup.com/t/86cwhb02y
> feat: adding card_mapping key in create_card_transactions API

- reference/admin.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@corporate_card_transactions@exports.yaml
- src/components/schemas/corporate_card_transactions_exports.yaml
- src/components/schemas/fields.yaml
[Please add link here](https://app.clickup.com/t/86cwvf0j9)
> feat: Add corporate card transactions exports api docs

- reference/approver.yaml
- src/components/schemas/expense.yaml
Reverting file_ids support from `POST approver/expenses` PR #552  because this change is not live yet and this restricts other folks from publishing the docs to v1 branch.
https://app.clickup.com/1864988/v/l/1rx8w-41176
> feat: Revert approver file ids

- reference/admin.yaml
- reference/approver.yaml
- src/components/schemas/expense.yaml
We are now enabling admin and approver APIs to update per diem expenses.
https://app.clickup.com/t/86cwxfya4
> feat: post approver/admin per_diem expenses~

- reference/spender.yaml
- src/components/schemas/expense.yaml
- src/spender/openapi.yaml
- src/spender/paths/spender@expenses@bulk.yaml
https://app.clickup.com/t/86cxnatdn
> feat: API spec for spender bulk edit expenses API

- reference/admin.yaml
- reference/spender.yaml
- src/admin/paths/admin@expense_policies.yaml
- src/spender/paths/spender@expense_policies.yaml
- This fixes the issue from specs [PR](https://github.com/fylein/fyle-platform-docs/pull/595) related to `/expense_policy_rules`
- The `is_approver_policy` param was defined as `boolean` causing platform-api tests to fail.
- Reason: query param value passed was `eq.true` which is not a valid `boolean` value.
- GET /spender/expense_policy_rules
- GET /admin/expense_policy_rules
https://app.clickup.com/t/86cxr6388
> fix: type fix for `GET /expense_policy_rules` query param `is_approver_policy`

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/components/schemas/fields.yaml
Updated specs for APIs returning `individual desired states` objects as response.
Fields added to `individual desired states` objects - 
- `approver_policy_order`
- `approver_order`
APIs updated - 
- GET /spender/expenses/expense_policy_states
- GET /approver/expenses/expense_policy_states
- GET /admin/expenses/expense_policy_states
- POST /spender/expenses/check_policies
- POST /spender/expenses/split/check_policies
- POST /approver/expenses/split/check_policies
- POST /admin/expenses/split/check_policies
- POST /spender/expenses/check_policies/bulk
https://app.clickup.com/t/86cxr0u83
> feat: updated specs post adding new fields to `individual desired states`

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/components/schemas/fields.yaml
Added `null` as an enum value for the `approver_source` field.
Reason -
- The `approver_source` field is defined as `nullable` but the `platform-api` yaml tests fail if these spec changes are included and some tests return `null` as a value for this field.
- This is due to some limitation/issue on `OpenAPI's` side.
Affected APIs - (by affected we mean those where `null` will be shown as an enum value for `approver_source` field)
- GET /spender/expenses/expense_policy_states
- GET /approver/expenses/expense_policy_states
- GET /admin/expenses/expense_policy_states
- POST /spender/expenses/check_policies
- POST /spender/expenses/split/check_policies
- POST /approver/expenses/split/check_policies
- POST /admin/expenses/split/check_policies
- POST /spender/expenses/check_policies/bulk …
> fix: added `null` to `approver_source` enum values

- reference/admin.yaml
- reference/spender.yaml
- src/components/schemas/expense_policies.yaml
We are adding the `source` field to specifically the `GET /expense_policy_rules` API response. This is required for FE to identify the `default primary approver policy`.
Updated APIs - 
- GET /spender/expense_policy_rules
- GET /admin/expense_policy_rules
- POST /admin/expense_policy_rules
- POST /admin/expense_policy_rules/enable
- POST /admin/expense_policy_rules/disable
https://app.clickup.com/t/86cy1wvy4
> feat: added `source` field to `expense_policy_rules` response

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/components/schemas/expense_policies.yaml
- src/components/schemas/report_approval.yaml
- We include the `report_approvals.rank` field in the `reports_rot.approvals` minimal objects array.
- This is required for `simplify_multi_stage_approvals` initiative.
- We have a UI requirement where the approvers of a report need to be shown in the sequence they are present in.
Updated APIs - 
- GET /spender/reports
- GET /approver/reports
- GET /admin/reports (including SS for `Response Sample` here)
Other APIs(create, submit, resubmit, add_approver, etc.) that return the entire `reports_rov/rot` in the response will also have this new field. But, the above APIs are the ones most relevant to us as of now.
https://app.clickup.com/t/86cy1wukp
> feat: add `rank` field to the `reports_rot.approvals` array objects.

- reference/admin.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@expense_policies@reorder.yaml
- Added new API to reorder approver policies.
- This is used for `simplified_multi_stage_approvals` feature.
API docs preview -
- POST /admin/expense_policy_rules/reorder
https://app.clickup.com/t/86cxr0j1t
> feat: `POST /admin/expense_policy_rules/reorder` API specs

- reference/admin.yaml
- reference/approver.yaml
- reference/spender.yaml
- src/admin/openapi.yaml
- src/admin/paths/admin@expenses@comments.yaml
- src/approver/openapi.yaml
- src/approver/paths/approver@expenses@comments.yaml
- src/components/parameters/expense_id.yaml
- src/components/schemas/expense.yaml
- src/components/schemas/fields.yaml
- src/spender/openapi.yaml
- src/spender/paths/spender@expenses@comments.yaml
- GET admin/expenses/comments
- GET approver/expenses/comments
- GET spender/expenses/comments
https://app.clickup.com/t/86cy1e3pr
> feat: Add Docs for Expense Comments `GET` APIs

- reference/admin.yaml
- src/components/schemas/fields.yaml
/admin/reminders API already supports cron format for recurring reminders, this PR updates the API docs to reflect this
https://app.clickup.com/t/86czjngaa
> feat: update API docs for /admin/reminders to show examples of cron format
