fylein/fyle-platform-docs

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@departments.yaml, src/admin/paths/admin@per_diem_rates.yaml, src/components/parameters/code.yaml, src/components/parameters/name.yaml, src/components/schemas/department.yaml, src/components/schemas/fields.yaml, src/components/schemas/per_diem_rate.yaml
=> Per diem rates and departments specs

reference/admin.yaml, src/components/schemas/expense_field.yaml
Added nullable to placeholder and default value
=> Fix expense fields response

reference/approver.yaml, reference/fyler.yaml, src/approver/openapi.yaml, src/fyler/openapi.yaml
Was getting Something went wrong for fyler and approver
https://fylein.slack.com/archives/C019TV6AZDH/p1636452835029200?thread_ts=1636451567.027600&cid=C019TV6AZDH
=> commented suggestions path from fyler and approver

.gitignore, reference/admin.yaml, reference/common.yaml, reference/spender.yaml, src/components/schemas/account.yaml, src/components/schemas/accounting_export.yaml, src/components/schemas/accounting_export_lineitem.yaml, src/components/schemas/adjustment.yaml, src/components/schemas/advance.yaml, src/components/schemas/advance_request.yaml, src/components/schemas/corporate_card.yaml, src/components/schemas/corporate_card_transaction.yaml, src/components/schemas/currency.yaml, src/components/schemas/expense_extract.yaml, src/components/schemas/expense_field.yaml, src/components/schemas/file.yaml, src/components/schemas/merchant.yaml, src/components/schemas/mileage_rate.yaml, src/components/schemas/place.yaml, src/components/schemas/policy.yaml, src/components/schemas/reimbursement.yaml, src/components/schemas/schedule.yaml, src/components/schemas/settlement.yaml
added `additionalProperties: false` to all the api out schemas. to check if any api is misbehaving.
https://app.clickup.com/t/23tzrzm
=> added additionalProperties: false to all out schemas

reference/admin.yaml, src/components/schemas/statement_mappings.yaml, src/components/schemas/statements.yaml
=> FYLE-2khcu33-vendor-to-merchant-rename

reference/spender.yaml, src/components/schemas/expense.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1fyuJi0XJCDyuaDBNM1VicMtjPqMT9Q%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=RWD-yiE)
=> fixed is_reimbursable description

reference/admin.yaml, reference/spender.yaml, src/admin/paths/admin@expense_policies.yaml, src/spender/paths/spender@expense_policies.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1klNzCILAN1AS83JqrvWLenv7pHJdiMWM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=53RsDeC)
=> Add is_retired filtering to admin/spender GET of policy rules

reference/admin.yaml, src/components/schemas/expense_policies.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX183BJzS6sKlWUwtQYrWGpX2OhiMguVOQo%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=MQMQDhQ)
=> expense policy rules POST params description update

reference/admin.yaml, reference/spender.yaml, src/components/schemas/expense_policies.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18kigpWclUc8xGtZyoD5f0S9WpoXt88m3k%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=7uP5N5M)
=> Add creator user in expense_policy_rules response

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml, src/components/schemas/expense_rules.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18EL6qRXHC9w0ORs6G5Qk3EiYGm13z0bcA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=qjszH5a)
=> Expense rules minor miss

docs/concepts/guide-data-apis.md
https://app.clickup.com/t/85zrn33hc
=> FYLE-85zrn33hc

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense_rules.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1oq4fqqs7tx5CoFJPPe3lSb6j1T0WHEM%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=XhwUqRb)
=> added `is_billable` and `purpose` to set object of expense_rules

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@upload.yaml, src/components/schemas/employee.yaml
Description:
Adding /admin/employees/uploads GET and POST APIs 
**Stoplight link:** https://fyle.stoplight.io/docs/fyle-platform-docs/branches/employees_upload/ff889a86456b6-list-employees-upload-requests
* you need to be signed in to stoplight to directly access the above link.
=> Employees upload APIs

admin.yaml, reference/admin.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml
Added changes for new keys in `GET` employees API
- locale
- mileage_settings
- ach_account
- delegatees
=> feat: Add docs for new keys in `GET` employees API

reference/spender.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@delete@bulk.yaml
Added open api spec for /spender/expense/delete/bulk under the initiative: Migrate my expeneses page to platform api.
Clickup: https://app.clickup.com/t/85zt3p7a2
=> Added expense delete bulk api spec

admin.yaml, reference/admin.yaml, reference/spender.yaml, src/admin/paths/admin@employees.yaml, src/components/schemas/fields.yaml
- Added query parameter to `GET /admin/employees` API
Clickup
https://app.clickup.com/t/85zrz4q7r
=> feat: Add query parameter for `GET /admin/employees`

reference/admin.yaml, src/admin/paths/admin@corporate_card_transactions.yaml
Changes
Added query parameter to GET /admin/corporate_card_transactions API
Standard import stuff
Clickup: https://app.clickup.com/t/85zt0r25j
=> feat: Add query parameter for GET /admin/corporate_card_transactions

admin.yaml, reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@business_units.yaml, src/admin/paths/admin@employees@locations.yaml, src/admin/paths/admin@employees@titles.yaml
Added following `GET` API docs:
- `/admin/employees/business_units`
- `/admin/employees/titles`
- `/admin/employees/locations`
=> feat: Add GET `business_units`, `titles` and `locations` API

admin.yaml, reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@reinvite@bulk.yaml, src/components/schemas/reinvitation.yaml
Added docs for employees `reinvite/bulk` API
Clickup: 
https://app.clickup.com/t/85zt90njx
=> feat: Employees `reinvite/bulk` API docs

admin.yaml, reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@filters.yaml, src/components/schemas/employee_filters.yaml, src/components/schemas/fields.yaml
https://app.clickup.com/t/85ztbhzqq
=> feat: Add employee saved filters `POST` API docs

reference/admin.yaml, src/components/schemas/fields.yaml
Added two fields in ach_transfer object for the new flow of simplify report closure
=> fix:added two new fields in reports

admin.yaml, reference/admin.yaml, src/admin/paths/admin@employees@filters.yaml
Adding docs for `/admin/employees/filters` GET API
Clickup: https://app.clickup.com/t/85ztbhh2z
=> feat: Add employee saved filters GET API docs

admin.yaml, reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@filters@delete.yaml, src/components/schemas/employee_filters.yaml
https://app.clickup.com/t/85ztbjgzm
=> feat: Add `employees/filters/delete` API docs

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@corporate_card_transactions@filters.yaml, src/admin/paths/admin@corporate_card_transactions@filters@delete.yaml, src/components/schemas/corporate_card_transaction_filters.yaml
Corporate card transactions saved filters get and delete apis
=> FYLE-85zt0r2au-saved-filters-get-delete-apis

admin.yaml, reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@downloads.yaml, src/components/schemas/employee.yaml
Adding `employees/downloads` GET and POST API docs.
=> feat: Add `employees/downloads` GET & POST API docs

admin.yaml, reference/admin.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml
Added `flattened_custom_field` in employees GET response.
Clickup: https://app.clickup.com/t/85ztkd6dp
=> feat: Add `flattened_custom_field` in employees `GET` response

reference/accountant.yaml, reference/admin.yaml, reference/spender.yaml, src/admin/paths/admin@files@generate_urls@bulk.yaml, src/components/schemas/file.yaml, src/spender/openapi.yaml, src/spender/paths/spender@files@generate_urls@bulk.yaml
Added new urls to generate s3 files upload and download urls for spender.
=> Added bulk file upload download urls for spender

docs/concepts/guide-data-apis.md
in reference to changes made to platform-api [here](https://github.com/fylein/fyle-platform-api/pull/1643)
=> feat: added abs operators to data API guide

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@filters.yaml, src/admin/paths/admin@expenses@filters@delete.yaml, src/components/schemas/expense_filters.yaml
Clickup: https://app.clickup.com/t/85ztmvhje
=> feat: added expense filters routes

reference/admin.yaml, src/components/schemas/fields.yaml
Clickup: https://app.clickup.com/t/85ztqtjrw
=> made status_info nullable in ach_transfer in reimbursment minimal object

reference/spender.yaml, src/components/schemas/report.yaml
Added the description for state
=> feat:updated the purpose description for spender

reference/admin.yaml, reference/spender.yaml, src/components/schemas/corporate_card_transaction.yaml
https://github.com/fylein/fyle-platform-api/pull/1659
=> feat: added can_delete in cct_rot

admin.yaml, reference/admin.yaml, reference/spender.yaml, src/components/schemas/corporate_card.yaml
https://github.com/fylein/fyle-platform-api/pull/1635
=> added card holder name and email in cct `corporate_card` key

reference/admin.yaml, src/components/schemas/employee.yaml
**Description:**
Added category_ids and categories fields in employee_out component
**Click Up**
https://app.clickup.com/t/85ztmx8xr
=> feat: Added category_ids and categories fields in employee_out component

reference/admin.yaml, src/components/schemas/employee.yaml, src/components/schemas/invitation.yaml
feat: Added category_names field on invitation component
Click UP
https://app.clickup.com/t/85ztmx8zz
=> feat: Added category_names field on invitation component

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@reports@create_and_submit.yaml, src/components/schemas/report.yaml
https://app.clickup.com/t/85ztmhqdj
=> feat: added api endpoint for admin create submit expenses

reference/admin.yaml, src/admin/paths/admin@advances.yaml, src/components/schemas/advance.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18PGzSxY8evIxz8q88FQOUSrDYXeeSYs%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=0gwzexZ)
=> fix: advances should not be updated

reference/admin.yaml, src/components/schemas/invitation.yaml
Clickup:
https://app.clickup.com/t/85ztu7tx0
=> feat: Update docs to show correct format for passing `project_names`

reference/admin.yaml, src/components/schemas/category.yaml
Added restricted spender user IDs field in POST categories APIs for admin persona
https://app.clickup.com/t/85ztr63nm
=> feat: Added restricted spender user IDs field in POST categories APIs for admin persona

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@accounting_export_summary@bulk.yaml, src/components/schemas/expense.yaml, src/components/schemas/report.yaml
API Contracts -> https://www.notion.so/fyleuniverse/API-Contracts-9bb0399b57c442a7b7c03b00773b671d#bd4980090d1d450eada80cf32a475ccf
=> feat: Add Accounting Export Summary to Expenses, Reports and POST of expenses/accounting_export_summary/bulk

reference/admin.yaml, src/components/schemas/corporate_card_transaction_filters.yaml, src/components/schemas/employee_filters.yaml, src/components/schemas/expense_filters.yaml, src/components/schemas/fields.yaml, src/components/schemas/report_filters.yaml
Changed `shared` to `is_shared`
=> FYLE-85zthcf8t-saved-filters-shared-fix

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@statements@card_stats.yaml, src/components/schemas/statements.yaml
API PR: https://github.com/fylein/fyle-platform-api/pull/1782
=> feat: Statement Card Stats API Docs

reference/admin.yaml, src/components/schemas/statements.yaml
API PR link: https://github.com/fylein/fyle-platform-api/pull/1782
=> fix: Statement card stats fields

reference/admin.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1822
=> feat: Statement card stats API

reference/admin.yaml, src/admin/paths/admin@statements@card_stats.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1822
=> fix: Statement card stats API examples

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@statements@post_missing_transactions.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1856
=> feat: POST `statements/missing_transactions` API docs

reference/admin.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1856
=> fix: changed ENUM value for `reconciliation_method`

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@statements@missing_transactions.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1881
=> feat: GET `statements/missing_transactions` API docs

reference/admin.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1884
=> feat: POST statements/create_card_transactions docs

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@scheduled_callbacks.yaml, src/components/schemas/fields.yaml, src/components/schemas/scheduled_callback.yaml
```json
{
"data": {
"url": "https://xyz.com/export",
"payload": {
"workspace_id": 10,
"API_KEY": "19824990xnjsikqi23"
},
"schedule_config": {
"type": "interval",
"when": {
"seconds": 5,
"end_date": "2023-10-01T00:00:00.000Z",
"start_date": "2023-09-29T00:00:00.000Z"
}
},
"is_enabled": true,
}
}
```
```json
{
"data": {
"id": "schtra1249xc",
"url": "https://xyz.com/export",
"payload": {
"workspace_id": 10,
"API_KEY": "19824990xnjsikqi23"
},
"schedule_config": {
"type": "interval",
"when": {
"end_date": "2023-10-01T00:00:00.000Z",
"seconds": 5,
"start_date": "2023-09-29T00:00:00.000Z"
}
},
"is_enabled": true,
"updated_at": "2023-09-30T08:04:45.424694+0000",
"created_at": "2023-09-30T08:04:45.424694+0000",
"org_id": "org1i24iks"
}
}
```
=> feat: Adding docs for admin/scheduled_callbacks

reference/admin.yaml, src/components/schemas/statements.yaml
https://github.com/fylein/fyle-platform-api/pull/1917
=> feat: Statements Card Stats - RTF Card Network

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/paths/admin@expenses.yaml, src/components/schemas/expense.yaml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1z1QHVCQeKQDfT5r9fX7UJIoJzYq5FtI%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=ZmyDXXZ)
https://app.clickup.com/t/8678zv3dw
=> feat: added POST `/admin/expenses` API

admin.yaml, reference/admin.yaml, src/components/schemas/fields.yaml
https://github.com/fylein/fyle-platform-api/pull/1968
=> fix: employee locale not nullable

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/t/86ctx0epq
=> feat: Added invoice number to api spec

reference/spender.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml
https://app.clickup.com/t/86ctvexbe
=> feat: Update spender employees docs

reference/approver.yaml, reference/spender.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@stats.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@stats.yaml
https://app.clickup.com/t/86cu0zpgc
=> feat: Added api specs for spender and approver stats api

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@filters.yaml, src/approver/paths/approver@expenses@filters@delete.yaml, src/components/schemas/fields.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@filters.yaml, src/spender/paths/spender@expenses@filters@delete.yaml
https://app.clickup.com/t/86cu17q8v
=> feat: added api spec for approver and spender expense filters

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@exports.yaml, src/approver/paths/approver@files@download.yaml, src/components/schemas/expenses_exports.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@exports.yaml, src/spender/paths/spender@files@download.yaml
https://app.clickup.com/t/86cu1tf42
=> feat: Added expenses exports spec for spender and approver

reference/spender.yaml, src/components/schemas/fields.yaml
Clickup: https://app.clickup.com/t/86cu158ur
=> feat: Update API contract for `GET spender/employees`

reference/spender.yaml, src/components/schemas/fields.yaml
Reverts fylein/fyle-platform-docs#420
=> fix: "feat: Update API contract for `GET spender/employees`"

reference/spender.yaml, src/components/schemas/fields.yaml
https://app.clickup.com/t/86cu158ur
=> feat: Update docs `GET spender/employees`

reference/spender.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@commute_details.yaml
https://app.clickup.com/t/86cu4yjyx
=> feat: Docs for `POST spender/commute_details`

reference/spender.yaml, src/components/schemas/expense.yaml
=> Added spec for file ids

docs/concepts/oauth2-application.md, reference/authorization.yaml, src/authorization/paths/oauth@token.yaml
https://app.clickup.com/t/86cu9947t
=> feat: Update docs to show authorization steps + fix `grant_type`

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml, src/components/schemas/fields.yaml
Clickup: https://app.clickup.com/t/86ctvexb6
=> feat: Add commute deduction keys for `GET /expenses`

reference/spender.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@commute_details@delete.yaml
https://app.clickup.com/t/86cucyeeg
=> feat: Docs for `commute_details/delete`

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml, src/components/schemas/fields.yaml
https://app.clickup.com/t/86cujaezy
=> feat: Make `commute_details` response nullable

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
Added advance_wallet_id to expense in/out at all places
=> feat: Add advance wallet id to expenses

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense_filters.yaml, src/components/schemas/fields.yaml
=> feat: Add sub_feature column in expense_filters

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@categories@delete_summary@bulk.yaml, src/components/schemas/category.yaml
feat: Added API Doc for categories/delete_summary/bulk API
=> feat: Added API Doc for categories/delete_summary/bulk API

reference/admin.yaml, src/components/schemas/category.yaml
feat: Fixed doc for categories/delete_summary/bulk
=> feat: Fixed doc for categories/delete_summary/bulk

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@reports@permissions.yaml, src/approver/openapi.yaml, src/approver/paths/approver@reports@permissions.yaml, src/components/schemas/report_permissions.yaml, src/spender/openapi.yaml, src/spender/paths/spender@reports@permissions.yaml
=> Added api specs for report permissions api

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@advances@bulk.yaml
https://app.clickup.com/t/86cudxpd7
=> feat: admin POST advances bulk

reference/admin.yaml, src/admin/openapi.yaml
=> Commented add approver api endpoint

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@reports@partially_approve@bulk.yaml
=> Added bulk partially_approve api for approver

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@projects@delete_summary@bulk.yaml, src/components/schemas/project.yaml
feat: Added API doc for projects/delete_summary/bulk
=> feat: Added API doc for projects/delete_summary/bulk

src/admin/openapi.yaml, src/admin/paths/admin@projects@delete@bulk.yaml
feat: Added API doc for projects/delete/bulk
=> feat: Added API doc for projects/delete/bulk

reference/admin.yaml, src/components/schemas/expense_field.yaml
https://app.clickup.com/t/86cuv6qvy
=> fix: removed column_name and is_custom from expense_fields api request body

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@advance_refunds.yaml, src/admin/paths/admin@advance_refunds@bulk.yaml, src/components/schemas/advance_refund.yaml
=> feat: Advance refunds

reference/admin.yaml, reference/spender.yaml, src/components/schemas/virtual_card.yaml
Added fields : virtual_card_user_id and nick_name
=> fix: updated fields in virtual_card_out

reference/admin.yaml, src/components/schemas/reimbursement.yaml
Click up:
https://app.clickup.com/t/86cutx2nx
=> fix: removed payment_id from reimbursements schema

reference/admin.yaml, reference/spender.yaml, src/components/schemas/advance.yaml, src/components/schemas/advance_request.yaml
=> feat: Add advance request approved time to advances API

reference/spender.yaml, src/components/schemas/feature_configs.yaml, src/spender/openapi.yaml, src/spender/paths/spender@feature_configs.yaml, src/spender/paths/spender@feature_configs@bulk.yaml
https://app.clickup.com/t/86cv86754
=> added feature_config api docs for spender

reference/admin.yaml, reference/approver.yaml, src/admin/openapi.yaml, src/admin/paths/admin@reports@add_approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@reports@add_approver.yaml, src/components/schemas/report.yaml
=> Added spec for add approver api

reference/admin.yaml, reference/spender.yaml, src/components/schemas/corporate_card.yaml
Clickup: https://app.clickup.com/t/86cvag3fx
=> feat: Update docs for `nickname` in `GET /corporate_cards`

.github/workflows/bundler.yml
https://app.clickup.com/t/86cvdvng5
=> feat: Run bundler for all branches

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@delete_files.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@delete_files.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@delete_files.yaml
=> fix: Reverted - Removed expenses/delete_files APIs

reference/admin.yaml, reference/approver.yaml, src/admin/openapi.yaml, src/admin/paths/admin@reports@send_back.yaml, src/approver/openapi.yaml, src/approver/paths/approver@reports@send_back.yaml, src/components/schemas/report.yaml
=> Added api spec for approver and admin send back report

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
=> feat: Add nickname to GET `/expenses`

reference/admin.yaml, src/admin/paths/admin@corporate_cards@masked_card_numbers.yaml, src/components/parameters/q_integer.yaml
https://app.clickup.com/t/86cvgutpy
=> feat: Add query params to `admin/corporate_cards/masked_card_numbers`

reference/admin.yaml, reference/spender.yaml, src/components/schemas/advance_request.yaml
https://app.clickup.com/t/86cvmp4xz
=> fix: Add adv req seq num to advances

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@reports@exports.yaml, src/approver/openapi.yaml, src/approver/paths/approver@reports@exports.yaml, src/components/schemas/reports_exports.yaml, src/spender/openapi.yaml, src/spender/paths/spender@reports@exports.yaml
=> Added API specs for admin, approver and spender report export

reference/admin.yaml, src/components/schemas/expense_policies.yaml
API docs changes with respect to https://github.com/fylein/fyle-platform-api/pull/2746
=> feat: Include payment mode attributes in receipt mandatory policies

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/reports_exports.yaml
=> Modified reports exports to include pdf export too

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml, src/components/schemas/expense_policies.yaml
https://app.clickup.com/t/86cvgqm17
=> feat: Deprecate Holidays and Weekends

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/paths/admin@reports@exports.yaml, src/approver/paths/approver@reports@exports.yaml, src/spender/paths/spender@reports@exports.yaml
=> Added spec for report export GET requests

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/paths/admin@reports@exports.yaml, src/approver/paths/approver@reports@exports.yaml, src/spender/paths/spender@reports@exports.yaml
=> Made report export get api as list api

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@potential_duplicate_expenses.yaml, src/components/schemas/employee.yaml
feat: Added documentation for /admin/employees/potential_duplicate_expenses API
=> feat: Added documentation for /admin/employees/potential_duplicate_expenses API

reference/admin.yaml, reference/approver.yaml, reference/hod.yaml, reference/hop.yaml, reference/spender.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml
https://app.clickup.com/t/86cvyyze1
=> feat: Update docs for `spender/employees`

reference/spender.yaml, src/components/schemas/employee.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@delegators.yaml
https://app.clickup.com/t/86cvyyzuc
Changes:
=> feat: Add `spender/employees/delegators` docs

.github/workflows/pr_checks_config.yaml
=> feat: Add GitHub PR Checks Workflow

reference/admin.yaml, reference/spender.yaml, src/components/schemas/employee.yaml, src/components/schemas/fields.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@delegatees.yaml
https://app.clickup.com/t/86cvyuukh
=> feat: Add `spender/employees/delegatees` docs

reference/spender.yaml, src/components/schemas/employee.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@delegatees@delete.yaml
https://app.clickup.com/t/86cw1fby7
=> feat: Add `spender/employees/delegatees/delete` docs

.github/pr-checks-config.yml, .github/pull_request_template.md, .github/workflows/pr-checks.yml, .github/workflows/pr-size.yml
https://app.clickup.com/t/86cwj8ynw
=> chore: Added github actions

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@corporate_cards@reassign.yaml, src/components/schemas/corporate_card.yaml
https://app.clickup.com/t/86cwk5fcq
=> feat: Add `POST admin/corporate_cards/reassign` API Docs

.github/workflows/pr-size.yml
https://app.clickup.com/t/86cwj8ynw
=> fix: PR Size CI Version Update

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@corporate_card_transactions@assign@bulk.yaml
https://app.clickup.com/t/86cwk5fva
=> feat: Add `POST admin/corporate_card_transactions/assign/bulk` API Docs

reference/admin.yaml, src/admin/openapi.yaml
https://app.clickup.com/t/86cwk5hhv
=> feat: Docs for `POST admin/corporate_card_transactions/ignore/bulk`

reference/admin.yaml, src/admin/paths/admin@statements@preview.yaml, src/components/schemas/statements.yaml
feat: added statement_card_number input in /preview API
https://app.clickup.com/t/86cwhazu7
=> feat: added statement_card_number input in /preview API

reference/admin.yaml, src/components/schemas/statements.yaml
feat: Added card_mapping key in /missing_transactions API
https://app.clickup.com/t/86cwhb000
=> feat: Added card_mapping key in /missing_transactions API

reference/admin.yaml, reference/spender.yaml, src/components/schemas/corporate_card_transaction.yaml
https://app.clickup.com/t/86cwpkxx5
=> feat: Added c1_virtual_card_last_four

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@cost_centers.yaml, src/components/schemas/cost_center.yaml
https://app.clickup.com/t/86cwtw2zu
=> feat: Added docs for `GET /approver/cost_centers`

reference/admin.yaml, src/components/schemas/statements.yaml
feat: Added user key in /matching_cards API
https://app.clickup.com/t/86cwhazp8
=> feat: Added user key in /matching_cards API

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@per_diem_rates.yaml
https://app.clickup.com/t/86cwtw4kg
=> feat: Added doc for `GET /approver/per_diem_rates`

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@per_diem_rates.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/t/86cwraakv
=> feat: Added c1_virtual_card_last_four to expense_out

reference/spender.yaml, src/components/schemas/personal_card.yaml
[clickup](https://app.clickup.com/t/86cwvuqtj)
[clickup](https://app.clickup.com/t/86cwvuqxw)
=> feat: Add support for account_type field in get personal cards

reference/spender.yaml, src/components/schemas/personal_card_transaction.yaml, src/spender/openapi.yaml, src/spender/paths/spender@personal_card_transactions@stats.yaml
=> Feat: add stats endpoint for personal card transactions

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/report_filters.yaml
Admin:
Spender:
Approver:
https://app.clickup.com/t/86cx5yxj4
=> feat: add sub_feature column in report filters

reference/admin.yaml, reference/approver.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/t/86cwxfya4
=> feat: post approver/admin per_diem expenses

reference/admin.yaml, reference/approver.yaml, src/components/schemas/expense.yaml
Reverts fylein/fyle-platform-docs#570
https://app.clickup.com/t/86cwxfya4
=> fix: Revert "feat: post approver/admin per_diem expenses"

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
Changed the per_diem_num_days from integer to number
https://app.clickup.com/t/86cx83zbh
=> feat: support fractional values for per_deim_num_days

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/1864988/v/l/li/901604687952
=> feat: Add group_by_state support to expenses stats API

reference/admin.yaml, reference/spender.yaml, src/components/schemas/advance_request.yaml
https://app.clickup.com/1864988/v/l/li/901604687952
=> feat: Add group_by_state support to advance request stats API

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/report.yaml
https://app.clickup.com/1864988/v/l/li/901604687952
=> feat: Add group_by_state support to reports stats API

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/advance_request.yaml, src/components/schemas/expense.yaml, src/components/schemas/report.yaml
https://app.clickup.com/1864988/v/l/li/901604687952
=> feat: Add group-by-state support to stats APIs for expenses, advance_requests, and reports

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/t/86cxbq4u3
=> feat: Allow mileage calculated fields in POST /<roles/expenses>

reference/spender.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@check_policies_bulk.yaml
https://app.clickup.com/t/86cxnaqkc
=> feat: Add API spec for check policies bulk API

reference/spender.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@check_mandatory_fields_bulk.yaml
https://app.clickup.com/t/86cxnatft
=> feat: API specs for spender/expenses/check_mandatory_fields/bulk

reference/admin.yaml, src/components/schemas/employee.yaml
add a new key to  `is_mobile_verified_key` GET admin/employees
app.clickup.com
=> Add is_mobile_verified_key

reference/spender.yaml, src/components/schemas/personal_card.yaml
https://app.clickup.com/t/86cxz7ehd
=> fix: invalid openAPI schema for personal_cards objects

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@employees.yaml
[Please add link here](https://app.clickup.com/t/86cxz8e77)
=> feat: added approver employees list api

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@permissions.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@permissions.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@permissions.yaml
https://app.clickup.com/t/86cwj4f85
=> feat: Add API docs for  `POST <role>/expenses/permissions` API

reference/spender.yaml, src/components/schemas/corporate_card_transaction.yaml
=> feat: Add corporate card id to spender cct and expenses stats api doc

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@advance_requests.yaml
=> feat: add approver advance requests api doc

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/corporate_card_transactions_exports.yaml, src/components/schemas/expenses_exports.yaml, src/components/schemas/reports_exports.yaml
[Please add link here](https://app.clickup.com/t/86cyc59pe)
=> fix: help article domain 

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@advance_requests@stats.yaml, src/components/schemas/advance_request.yaml
[app](https://app.clickup.com/t/86cxz8ny9)
=> feat: Add approver advance requests stats api docs

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/fields.yaml
feat: Making state, country, city as nullable fields in commute details
https://app.clickup.com/t/86cy4d3k8
=> feat: Making state, country, city as nullable fields in commute details

reference/admin.yaml, src/components/schemas/org.yaml
https://app.clickup.com/t/86cy6wxed
=> feat: updated schema for get /admin/orgs api response

reference/admin.yaml, src/components/schemas/org.yaml
=> fix: removed new fields from required section in orgs api

reference/spender.yaml, src/components/schemas/org.yaml, src/spender/openapi.yaml, src/spender/paths/spender@orgs.yaml
https://app.clickup.com/t/86cy6wxx5
=> feat: added schema for new api: GET /spender/orgs

reference/admin.yaml, reference/spender.yaml, src/components/schemas/org.yaml
https://app.clickup.com/t/86cyh1y63
=> feat: Updated response schema of orgs get api

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@orgs_bank_details.yaml, src/components/schemas/org.yaml
https://app.clickup.com/t/86cyh1vab
=> feat: added schema for new api - org bank details

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employees@summaries.yaml, src/components/schemas/employee.yaml
=> feat: Add admin employee summaries list api docs

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@merchants.yaml
[Please add link here](https://app.clickup.com/t/86cynfuzb)
=> feat: add admin merchants api docs

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@verify@bulk.yaml, src/components/schemas/expense.yaml
https://app.clickup.com/t/86cy5qanc
=> feat: Add API spec for `POST /admin/expenses/verify/bulk` API

reference/spender.yaml, src/components/schemas/recently_used_fields.yaml, src/spender/openapi.yaml, src/spender/paths/spender@recently_used_fields.yaml
=> feat: recently used fields api docs

reference/spender.yaml, src/spender/openapi.yaml
https://app.clickup.com/t/86cwj7byg
=> Feat:FYLE-86cwj7byg-added API spec for expense_bulk_delete

reference/admin.yaml, reference/spender.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml
https://app.clickup.com/t/86cyt95j7
=> Fix:Fyle-86cyt95j7-make spent at optional

reference/spender.yaml, src/components/schemas/corporate_card.yaml, src/spender/openapi.yaml, src/spender/paths/spender@corporate_cards@yodlee_accounts.yaml
https://app.clickup.com/t/86cyb97vx
=> feat: Add docs for new endpoint to get yodlee corporate cards

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@comments@bulk.yaml, src/approver/openapi.yaml, src/approver/paths/approver@expenses@comments@bulk.yaml, src/components/schemas/expense.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@comments@bulk.yaml
- POST admin/expenses/comments/bulk
- POST approver/expenses/comments/bulk
- POST spender/expenses/comments/bulk
app.clickup.com
=> feat: POST role/expenses/comments/bulk

reference/admin.yaml, reference/spender.yaml, src/components/schemas/org.yaml, src/spender/openapi.yaml, src/spender/paths/spender@orgs_bank_details.yaml
https://app.clickup.com/t/86cyh1vab
=> feat: Added new api spender orgs bank details

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@delete@bulk.yaml
https://app.clickup.com/t/86cwj7byg
=> Feat:Add bulk delete endpoint to admin API spec

reference/approver.yaml, src/approver/openapi.yaml
Added missing tag
https://app.clickup.com/t/86cyzzhkf
=> fix: add accounts to list of approver tags in openapi spec

reference/admin.yaml, reference/spender.yaml, src/components/schemas/corporate_card.yaml
https://app.clickup.com/t/86cyb8x7y
=> fix: Add yodlee_account_id to corporate cards response

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expenses@merge.yaml, src/components/schemas/expense.yaml
[Please add link here](https://app.clickup.com/t/86cyxgtz2)
=> feat: Add api doc for admin expenses merge api

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/schemas/advance_request.yaml
https://app.clickup.com/t/86cz57axf
=> feat: updated response of advance request out schema

reference/spender.yaml, src/spender/openapi.yaml, src/spender/paths/spender@advance_requests@submit.yaml
https://app.clickup.com/t/86cz57axf
=> feat: added docs for advance request submit api

reference/spender.yaml, src/spender/openapi.yaml, src/spender/paths/spender@expenses@merge.yaml
[Please add link here](https://app.clickup.com/t/86cyxgujg)
=> feat: Added spender expense merge api doc

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@advance_requests@bulk_attach_file.yaml, src/approver/openapi.yaml, src/approver/paths/approver@advance_requests@bulk_attach_file.yaml, src/components/schemas/advance_request.yaml, src/spender/openapi.yaml, src/spender/paths/spender@advance_requests@bulk_attach_file.yaml
https://app.clickup.com/t/86cz57h2h
=> feat: Schema for new api: advance request bulk attach files

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/admin/openapi.yaml, src/admin/paths/admin@employee@settings.yaml, src/approver/openapi.yaml, src/approver/paths/approver@employee@settings.yaml, src/components/schemas/employee_settings.yaml, src/spender/paths/spender@employee@settings.yaml
Please add link [here](https://app.clickup.com/t/86cz8jb6d)
=> feat: FYLE-86cyxp6pn-employee-settings-admin-changes

.github/workflows/secrets-scan.yml
https://app.clickup.com/t/86cz45anq
=> fix: minor typo fix in secrets scan

reference/spender.yaml, src/components/schemas/advance_request.yaml, src/spender/openapi.yaml, src/spender/paths/spender@advance_requests@delete.yaml
https://app.clickup.com/t/86czbaxdu
=> feat: Added api docs for advance request delete api

reference/admin.yaml, reference/approver.yaml, reference/spender.yaml, src/components/parameters/state.yaml, src/components/schemas/expense.yaml, src/components/schemas/fields.yaml
=> feat: Update API contracts for new critical policy violation flow

reference/spender.yaml, src/components/schemas/employee_settings.yaml
Please add link [here](https://app.clickup.com/t/86cz8jbaw)
=> fix: FYLE-86cz8jbaw-locale-fix

reference/spender.yaml, src/components/schemas/409.yaml, src/spender/paths/spender@secondary_emails.yaml, src/spender/paths/spender@secondary_emails@check.yaml
=> fix: secondary emails status code

reference/spender.yaml, src/components/schemas/employee.yaml, src/spender/openapi.yaml, src/spender/paths/spender@employees@check_mobile_verification_code.yaml
[Please add link here](https://app.clickup.com/t/86czwg7rw)
=> feat: Add check mobile verification code api docs

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@merchants.yaml, src/components/schemas/merchant.yaml
=> feat: GET approver/merchant API

reference/approver.yaml, src/approver/openapi.yaml, src/approver/paths/approver@employee_overview@stats.yaml, src/components/schemas/employee.yaml
https://app.clickup.com/t/86d086vt2
=> feat: Added api docs for employee overview stats api

reference/admin.yaml, src/admin/openapi.yaml, src/admin/paths/admin@expense_rules@dismiss_suggestion.yaml, src/components/schemas/expense_rules.yaml, src/components/schemas/fields.yaml
- Add /dismiss_suggestion API
- Add new columns for expense rule suggestions
- Update project_id to nullable in `expense_rule_data_out` for ERS tests on platform-api to pass
https://app.clickup.com/t/86d0drf4b
=> feat: changes related to expense rule suggestions
